services:
  dev-server-go:
    image: server-go
    container_name: dev-server-go
    ports:
      - "8081:8080"
    volumes:
      - ./server:/app
    entrypoint: ["bash"]
    stdin_open: true
    tty: true

  server-go:
    image: server-go
    container_name: running-server-go
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    environment:
      - SERVER_ADDR=:8080

  client-react:
    image: client-react
    container_name: running-client-react
    ports:
      - "3000:3000"
    depends_on:
      - server-go
    volumes:
      - ./client:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

    environment:
      - REACT_APP_API_HOST=localhost:8080
      - REACT_APP_PROTOCOL=http
